baseURL: https://ltao.top/
languageCode: 'zh-cn'
timeZone: "Asia/Shanghai"
languageCode: 'zh-cn'
defaultContentLanguage: 'zh-cn'
defaultContentLang: 'zh-cn'
title: '流笔'
theme: 'note'
port: 80
enableGitInfo: true
# disableKinds:
#   - "section"
#
frontmatter:
  publishDate:
    - datetimeCreate
  lastmod:
    - datetimeUpdate
markup:
  defaultMarkdownHandler: "goldmark"
  markup.highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  tableOfContents:
    startLevel: 1
    endLevel: 6

# 自定义参数
params:
  # 笔记本创建日期
  buildDate: "2023-02-25" 
  
  # 目录最大深度
  BookToCMax: 4

  # 深色开关：默认浅色，light，dark，auto（基于浏览器系统设置）
  BookTheme: "auto"

  # 目录开关
  BookToC: false


  # 笔记文件夹
  BookSection: "/notes"

  # 日期格式 ， "2006-01-02 15:04"
  BookDateFormat: {"minute":"4分钟前","hour":'3小时前',"month":'1-2',"year":"2006-01-02 15:05"}

  # 搜索开关：可选，默认True
  BookSearch: true

  # 评论开关：可选，默认false
  BookComments: true

  # ：可选，默认false，
  BookPortableLinks: true

  # 是否使用离线缓存：可选，默认false，
  BookServiceWorker: true

  # 是否翻译：可选，默认false，
  BookTranslatedOnly: false 